// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DropImplant(arg1) {
  return window['go']['main']['App']['DropImplant'](arg1);
}

export function Hello(arg1) {
  return window['go']['main']['App']['Hello'](arg1);
}

export function ListBofs() {
  return window['go']['main']['App']['ListBofs']();
}

export function ListImplants() {
  return window['go']['main']['App']['ListImplants']();
}

export function RunBofByB64(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBofByB64'](arg1, arg2, arg3);
}

export function RunBofByName(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBofByName'](arg1, arg2, arg3);
}

export function UploadBof(arg1, arg2) {
  return window['go']['main']['App']['UploadBof'](arg1, arg2);
}
