// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DropImplant(arg1:number):Promise<void>;

export function Hello(arg1:number):Promise<void>;

export function ListBofs():Promise<Array<main.BofEntry>>;

export function ListImplants():Promise<Array<main.Implant>>;

export function RunBofByB64(arg1:number,arg2:string,arg3:string):Promise<void>;

export function RunBofByName(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UploadBof(arg1:string,arg2:string):Promise<void>;
